# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "STP PhTestCon 2018"
email: "softwaretestingphilippines@gmail.com"
description: "STP PhTestCon is a yearly event for testing practitioners in the Philippines. Organized by Software Testing Philippines - Core Group who are passionate testing and quality leaders and practitioners who aims to build a strong testing industry in The Philippines through meetups, trainings, conferences, and events."
baseurl: ""
url: "https://www.phtestcon.com"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-123711923-1"
googleAnalyticsSiteUrl: "phtestcon.com"
siteVerification: "CI-Fzu86h4BanNIRPYJbsm0SShbA7DveLHGXvp1i-KI"

# Organizer Info
organizerName: "STP Core"
organizerAlternateName: "STP Core Group"
organizerDescription: "Open and volunteer testing enthusiast and practitioner who share experience about Software Testing with passion."
organizerEmail: "softwaretestingphilippines@gmail.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://lviv.gdg.org.ua/"

# Head
metaKeywords: "event, stp, phtestcon, google, testng, android, chrome, testers"
twitterAccount: "@DevFest"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebookSTP: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "http://bit.ly/phtestcon2018"
#c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
# - {permalink: "/blog/", text: "Blog"}
# - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Logistics"}
# - {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 - {link: "http://bit.ly/phtestcon2018", text: "Become a speaker"}
rightNavigationButtons:
 - {link: "http://bit.ly/phtestcon2018", text: "Become a speaker"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "STP PhTestCon <typeout> 2018"
eventDate: "November 17, 2018"
typeoutTextValues: '"", "Season", "Manila", "Philippines"'
typeoutFallback: "Season"
heroButtons:
 - {link: "http://bit.ly/phtestcon2018", text: "Become a speaker"}
 - {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "About STP PhTestCon"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "The biggest Google related event in the country carefully crafted for you by GDG community! Awesome speakers and lots of fun!" }
 - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }
 - {title: "Hackathon", image: "hackathon.jpg", text: "Full-day freestyle hackathon! Want some real team building on friday? Grab your team and join our hackathon!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "170", specialCharacter: "+", info: "attendees", detail: "from NCR"}
 - {count: "8", specialCharacter: "+", info: "hours", detail: "of pure Testing topics"}
 - {count: "14", specialCharacter: "+", info: "speakers", detail: "from different companies"}
 - {count: "3", specialCharacter: "", info: "parallel talks", detail: "plus games and raffles"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Featured speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "WCC (BGC)"
eventLocationName: "Willis Towers Watson, 23rd Floor"
eventLocationLink: "https://www.phtestcon.com/"
eventStreetAddress: "30th Street corner 7th Avenue"
eventAddressLocality: "BGC"
eventAddressLocalityRegion: "Taguig"
eventPostalCode: "1630"
eventAddressCountry: "Philippines"
eventStartTime: "2018-11-17T08:00"
eventDoorTime: "07:00"
eventEndTime: "2018-11-17T18:00"
eventPlaceCoordinates: "14.552954, 121.049704"
mapCenterCoordinates: "14.552954, 121.049704"
mapMobileCenterCoordinates: "14.552820, 121.049836"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "WTW Conference Hall"
venueFeatures: ["1 huge hall", "Digital audio system", "Located inside WTW Office at W City Center"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "phtestcon2018"
#twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
#partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee breaks, lunch and snacks."
ticketsOffers:
 -
  name: "Early Bird"
  price: "2500"
  priceCurrency: "PHP"
  #ticketsNumber: "30"
  #ribbon: "-29%"
  featured: true
  buyButtonLink: "http://bit.ly/phtestcon2018ticket"
  buyButtonText: "Buy Now"
  ticketContentList: ["Software Testing Philippines", "Volunteer-organized software testing conference", "#PHTESTCON2018"]
  validFrom: "2018-09-21T00:01"
  validThrough: "2018-10-15"
  #disabled: false
  soldOut: true
  soldOutText: "Sold Out"
 -
  name: "Regular Rate"
  price: "3500"
  priceCurrency: "PHP"
  #ticketsNumber: "80"
  ribbon:
  #featured: true
  buyButtonLink: "http://bit.ly/phtestcon2018ticket"
  buyButtonText: "Buy Now"
  ticketContentList: ["Software Testing Philippines", "Volunteer-organized software testing conference", "#PHTESTCON2018"]
  validFrom: "2018-10-16T00:01"
  validThrough: "2018-11-15T23:59"
  disabled: false
 -
  name: "Early Bird"
  price: "2500"
  priceCurrency: "PHP"
  #ticketsNumber: "30"
  #ribbon: "-29%"
  featured: true
  buyButtonLink: "http://bit.ly/phtestcon2018ticket"
  buyButtonText: "Buy Now"
  ticketContentList: ["Software Testing Philippines", "Volunteer-organized software testing conference", "#PHTESTCON2018"]
  validFrom: "2018-09-21T00:01"
  validThrough: "2018-10-15"
  #disabled: false
  soldOut: true
  soldOutText: "Sold Out"

# Footer
socialLinks:
# - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://twitter.com/testers_ph", icon: "twitter"}
 - {link: "https://www.facebook.com/groups/softwaretestingphilippines/", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   #- {link: "http://gdg.org.ua", text: "GDG.org.ua"}
   #- {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:softwaretestingphilippines@gmail.com", text: "GMAIL"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "We are passionate testing and quality leaders and practitioners who aims to build a strong testing industry in The Philippines through meetups, trainings, conferences, and events to showcase the Filipino skill.
          <br><br>
          Our vision is to get the Philippine Software Testing community known worldwide!"

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "14.552954, 121.049704"
logisticsMapMobileCenterCoordinates: "14.552954, 121.049704"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around BGC"
directionDetailsCards:
- {title: "From the Airport", information: 'Manila Airport - NAIA is located along the border between Pasay City and Parañaque City in Metro Manila. It is easily reachable by car, public transport or taxi. <a href="http://www.ubeexpress.com/">Premium Bus Service</a> is also an option going to Makati, then take BGC Bus going to event place (See Public Transit).'}
- {title: "Public Transit", information: 'First, you need to get to the exact location of MRT Ayala Station. You can get there either by bus or by train. Second, go down to northbound lane of EDSA which is the lane opposite SM Makati. There is only one stair there. Get inside BGC Bus Terminal and buy ticket going to East Bus Route.'}
# - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
# -
#  title: "Questions?"
#  subCards:
#   -
#    title: "Hotels"
#    links:
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#   -
#    title: "Registration"
#    links:
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#   -
#    title: "Attendance Details"
#    links:
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
