# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENCE.txt', 'CNAME']


# Site Settings
title: "GDG DevFest Fresno 2015"
email: "james.cha.zero@gmail.com"
description: "GDG DevFest is a set of events all around the world"
baseurl: ""
url: "http://gdgfresno.github.io/"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "gdg-x.github.io"

# Organizer Info
organizerName: "Rio Waller and James Cha"
organizerAlternateName: "Google Developer Group Fresno"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "gdgfresno@gdgfresno.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://gdgfresno.com/"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, Fresno, Centravl Vally, California"
twitterAccount: "@DevFest"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "http://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "http://www.eventbrite.com/e/fresno-devfest-2015-tickets-18266248842", text: "Tickets"}
 - {link: "https://developers.google.com", text: "Developers"}
#bottomNavigationLinks:
# - {link: "https://www.eventbrite.com/e/fresno-devfest-2015-tickets-1826624884", text: "Get Your Ticket!"}
#rightNavigationButtons:
# - {link: "https://www.eventbrite.com/e/fresno-devfest-2015-tickets-1826624884", text: "Get Your Ticket!"}

# Hero Block
heroTitle: "October 17 2015  "
eventDate: "GDG Fresno, GDG Oakdale and GDG Visalia"
typeoutTextValues: '"SAVE THE DATE"'
typeoutFallback: "Season"
#heroButtons:
# - {url: "http://goo.gl/aCMR8A", text: "Become a speaker"}

# About Block
aboutTitle: "About GDG DevFest"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "The biggest Google related event in the California Central Valley carefully crafted for you by your local GDG community! Awesome speakers and lot's of fun!" }
 - {title: "Workshops", image: "workshop.jpg", text: "Full day of workshops, hands-on experience, hacking and debugging. Come and tame your favorite technology!" }
 - {title: "Hackathon", image: "hackathon.jpg", text: "Full day freestyle Design Sprints! Want some real teambuilding on friday? Grab your team and join our hackathon!" }

# Statistic Block
aboutTitle: "Statistics for 2014 DevFest"
statisticBlock:
 - {count: "320", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "8", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from our community and beyond"}
 - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Latest News Block
latestNewsTitle: "Latest news"

#Rockstar Speakers Block
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Fresno City College OAB"
eventLocationLink: "http://www.fresnocitycollege.edu/"
eventStreetAddress: "1101 E University Ave"
eventAddressLocality: "Fresno"
eventAddressLocalityRegion: "California"
eventPostalCode: "93741"
eventAddressCountry: "US"
eventStartTime: "2015-10-17T010:00"
eventDoorTime: "10:00"
eventEndTime: "2015-10-17T16:00"
eventPlaceCoordinates: "36.768592,-119.795866"
mapCenterCoordinates: "36.768592,-119.795866"
mapMobileCenterCoordinates: "36.768592,-119.795866"

# Venue Block
venueBlockTitle: "Venue"
venueTitle: "Fresno City College"
venueFeatures: ["OAB","Old Administration Building","Completed in 1916 and restored in 2011"]

# Tweets Feed Block
tweetsFeedTitle: "What's Up?"
twitterHashTag: "devfest"
twitterFeed: "https://twitter.com/GDGFresno/tweetledee/favoritesjson.php?c=10&cache_interval=900"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeTitle: "Subscribe for updates"
subscribeAction: "http://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
#ticketsTitle: "Pricetable"
#ticketsInfo: "Tickets grant access to all conference sections, coffee breaks, lunch and party. Accommodation is NOT included in the ticket price."
#ticketsOffers:
# -
#  name: "Student"
#  price: "10"
#  priceCurrency: "Dollars"
#  ticketsNumber: "50"
#  buyButtonLink: "http://www.eventbrite.com/e/fresno-devfest-2014-tickets-12537823969"
#  buyButtonText: "Buy Now"
#  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund."
#  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
#  validFrom: "2014-08-20T10:00"
#  validThrough: "2014-10-17T23:59"
# -
#  name: "Teachers"
#  price: "20"
#  priceCurrency: "Dollars"
#  ticketsNumber: "50"
#  buyButtonLink: "http://www.eventbrite.com/e/fresno-devfest-2014-tickets-12537823969"
#  buyButtonText: "Buy Now"
#  additionalInfo: "Contact us directly for special pricing for your students."
#  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
#  validFrom: "2014-08-20T10:00"
#  validThrough: "2014-10-17T23:59"
# -
#  name: "Developers"
#  price: "20"
#  priceCurrency: "Dollars"
#  ticketsNumber: "50"
#  buyButtonLink: "http://www.eventbrite.com/e/fresno-devfest-2014-tickets-12537823969"
#  buyButtonText: "Buy Now"
#  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
#  validFrom: "2014-08-20T10:00"
#  validThrough: "2014-10-17T23:59"
# -
#  name: "Last Chance"
#  price: "25"
#  priceCurrency: "Dollars"
#  ticketsNumber: "50"
#  buyButtonLink: "http://www.eventbrite.com/e/fresno-devfest-2014-tickets-12537823969"
#  buyButtonText: "Buy Now"
#  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
#  validFrom: "2014-10-18T00:00"
#  validThrough: "2014-10-18T23:59"
#  disabled: true

# Footer
socialLinks:
 - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=GDGFresno", icon: "twitter"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www.gdgfresno.com", text: "GDGFresno.com"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:gdgfresno@gdgfresno.com", text: "gdgfresno@gdgfresno.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true
thumbnailsFolder: /img/speakers/

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google’s services have become synonymous with online simplicity/ease of use/usability. The breadth of technological innovations and IT industries in which Google is creating new products is enormous. Realistically, it is hard for any individual user to grow and stay familiar with Google’s variety. This is why people have started to gather in small, local groups to share their learning and experiences. Gradually, these groups were called Google Developer Groups (GDGs). GDGs can take many forms—from a handful of people gathering together to watch some videos to large gatherings with demonstrations, tech talks, hackathons and conferences. GDG DevFest Fresno 2015 is organized by three C GDGs: Fresno, Oakdale and Visalia."

# Logistics Find Way Block
findWayTitle: "Find your way here"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"

# Logistics Direction Details Block
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards: 
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   - 
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
