# Build settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENCE.txt', 'CNAME']


# Site settings
title: GDG Bangalore
email: gdg-bangalore-organizers@googlegroups.com
description: "Google Developer Group Bangalore"
baseurl: "/GDG-Bangalore"
url: "http://kartikkannapur.github.io/"
permalink: /blog/:title
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: "http://kartikkannapur.github.io/GDG-Bangalore"



#Tweets feed
twitterHashTag: "gdgbangalore"

# Subscribe
subscribeAction: ""

# Documents
c4pUrl: "http://goo.gl/Y1uhch"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"

# Head
metaKeywords: "event, gdg, gdgbangalore,devfest, google, programming, android, chrome, developers"
twitterAccount: "@GTUG_BLR"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Header
eventDate: "Google Developer Group Bangalore"
typeoutTextValues: '"Ads","Analytics","Android","Apps","Chrome","Cloud","Glass","Google+","Maps","YouTube"'

# About Event Block
eventName: "GDG Bangalore"

# Team Block
aboutUs: Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences.

# Speakers List Block
showSessions: true
thumbnailsFolder: /img/speakers/

# Footer
gplusFollowUsUrl: "https://plus.google.com/104550553343399000979"
twitterFollowUsUrl: "https://twitter.com/GTUG_BLR"
fbFollowUsUrl: "https://www.facebook.com/groups/133702039437/"

# Blog
blogCommentsEnabled: true
discusShortName: "GDG Bangalore"
