# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "BSides Halifax Quarantine Edition"
email: "info@bsideshalifax.ca"
description: "BSides is a community-driven framework for building events for and by information security community members."
baseurl: ""
url: "https://bsideshalifax.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "gdg-x.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "BSides Halifax"
organizerAlternateName: "Halifax BSides"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Cyber Security with passion."
organizerEmail: "info@bsideshalifax.ca"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://bsideshalifax.ca"

# Head
metaKeywords: "event, BSides, Halifax, Cyber, Security, infosec"
twitterAccount: "@defcon902"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"

# Documents
# c4pUrl: "https://bit.ly/dfua-c4p"
# c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 #- {permalink: "/blog/", text: "Blog"}
#  - {permalink: "/schedule/", text: "Schedule"}
#  - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
 #- {permalink: "/logistics/", text: "Logistics"}
 - {permalink: "/hackathon/", text: "Hackathon"}
#bottomNavigationLinks:
# - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
#rightNavigationButtons:
# - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}

# Hero Block
heroImage: "halifax.jpg"
heroTitle: "BSides Halifax <typeout> 2020"
eventDate: "Friday May 22, 2020"
typeoutTextValues: '"", "Virtual", "Quarantine Edition", "Stay The Blazes Home", "Donair Bonanza"'
typeoutFallback: "Virtual"
heroButtons:
#  - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
 - {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "About BSides Halifax"
aboutBlock:
 - {
    title: "Conference",
    image: "conference.jpg",
    text: "<p>In Halifax, we usually host a conference called AtlSecCon (Atlantic Security Conference) this time of year. And 2020 was going to be the best year ever! It was the tenth anniversary, and everyone was really looking forward to a party... in a big crowded room... with plenty of people constantly breathing in and out...</p>
<p>Anyway, things have changed, and AtlSecCon's tenth anniversary will now be held in 2020++ (aka 2021). But that doesn't mean security takes a break!</p>
<p>In fact, since we're all online more than ever, it's the perfect time to examine your personal and professional security posture, to see if there's anything that could be improved, or any holes that need patching.</p>
<p>We'll be hosting BSides Halifax on May 22nd, and you can attend from the safety of your home/secured bunker/government-mandated temporary quarantine facility by logging on to bsideshalifax.ca at 10AM Atlantic (9AM Eastern).</p>
<p>We're really appreciative of everyone who's come forward to help us out with this. Tickets are $13.37 CAD, and all money raised will go to Feed Nova Scotia, who make sure no Nova Scotian goes hungry. We look forward to seeing you all soon!</p>"
}
# - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }
 #- {title: "Hackathon", image: "hackathon.jpg", text: "Full-day freestyle hackathon! Want some real team building on friday? Grab your team and join our hackathon!" }

# Statistic Block
# statisticBlockImage: "statistic.jpg"
# statisticBlock:
#  - {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
#  - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
#  - {count: "20", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
#  - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Latest News Block
# latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 3
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
# locationBlockTitle: "Location"
# eventLocationName: "Conference Hall"
# eventLocationLink: "http://cabinet.kinopalace.lviv.ua/showtimes/"
# eventStreetAddress: "22 Teatral'na St"
# eventAddressLocality: "Lviv"
# eventAddressLocalityRegion: "Lvivska"
# eventPostalCode: "79000"
# eventAddressCountry: "Ukraine"
# eventStartTime: "2014-10-25T10:00"
# eventDoorTime: "09:00"
# eventEndTime: "2014-10-25T20:00"
# eventPlaceCoordinates: "49.843237, 24.028751"
# mapCenterCoordinates: "49.842537, 24.025701"
# mapMobileCenterCoordinates: "49.841620, 24.029411"

# Venue Block
# venueBlockTitle: "Venue"
# venueBigImage: "venue_0.jpg"
# venueSmallImage1: "venue_1.jpg"
# venueSmallImage2: "venue_2.jpg"
# venueSmallImage3: "venue_3.jpg"
# venueTitle: "Kinopalace Cinema"
# venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# Tweets Feed Block
# tweetsFeedImage: "twitter-feed.jpg"
# tweetsFeedTitle: "What's Up?"
# twitterHashTag: "devfest"
# twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
# subscribeImage: "subscribe.jpg"
# subscribeTitle: "Subscribe for updates"
# subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
# subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Tickets"
ticketsInfo: "All proceeds to go Feed Nova Scotia"
ticketsOffers:
 -
  name: "General Admittance"
  price: "13.37"
  priceCurrency: "CAD"
#   ticketsNumber: "150"
#   ribbon: "-5%"
  buyButtonLink: "https://www.eventbrite.ca/e/security-bsides-halifax-2020-virtual-tickets-104057223958?aff=ebdssbeac"
  buyButtonText: "Buy Now"
  ticketContentList: ["Access to amazing talks", "Admittance to our CTF", "Our everlasting love and admiration", "All proceeds to go Feed Nova Scotia"]
#   validFrom: "2014-08-25T10:00"
#   validThrough: "2014-09-30T23:59"

# Footer
socialLinks:
 - {link: "https://twitter.com/intent/user?screen_name=HalifaxBSides", icon: "twitter"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www.securitybsides.com/w/page/12194156/FrontPage", text: "Security BSides"}
   - {link: "https://atlseccon.com", text: "Atlantic Security Conference"}
   - {link: "https://dc902.ca", text: "DEFCON Halifax"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:info@bsideshalifax.ca", text: "info@bsideshalifax.ca"}
 -
  title: "Code of Conduct"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
# blogTitle: "Latest news"
# blogCommentsEnabled: true
# discusShortName: "devfestua"

# Speakers List Block
showSessions: false

# Team Block
# teamBlockTitle: "About us"
# aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
# findWayTitle: "Find your way here"
# findWayDistance: "Distance"
# findWayDriving: "DRIVING"
# findWayWalking: "WALKING"
# findWayBicycling: "BICYCLING"
# findWayTransit: "TRANSIT"
# findWayFindFlight: "Find Flight"
# logisticsMapCenterCoordinates: "49.056728, 3.117289"
# logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
# logisticsMapAutoDirections: false

# Logistics Direction Details Block
# directionDetailsImage: "direction-details.jpg"
# directionDetailsTitle: "Get around Lviv"
# directionDetailsCards:
#  - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
#  - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
#  - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
# directionDetailsWideCards:
#  -
#   title: "Questions?"
#   subCards:
#    -
#     title: "Hotels"
#     links:
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#    -
#     title: "Registration"
#     links:
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#    -
#     title: "Attendance Details"
#     links:
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "CMD+CTRL"
hackathonRows:
   - {title: "", image: "hackathon-0.png", details: "<p>Stuck at home, but still want to test your skills in identifying web app vulnerabilities?  BSides Halifax and Security Innovation invite players to virtually compete in CMD+CTRL, a web application cyber range where players exploit their way through hundreds of vulnerabilities that lurk in business applications today.  Success means learning quickly that attack and defense is all about thinking on your feet.</p>
<p>For each vulnerability you uncover, you are awarded points. Climb the interactive leaderboard for a chance to win fantastic prizes! CMD+CTRL is ideal for development teams to train and develop skills, but anyone involved in keeping your organizationâ€™s data secure can play - from developers and managers and even CISOs.</p>
<p>All you need is your laptop and inner evil-doer!</p>
<br />
<p>Register early to reserve your spot and get a sneak peek at our cheat sheets and FAQs!</p>"}

# Hackathon Judges Block
# judgesImage: "judges.jpg"
# judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Hak5 Bash Bunny"}
 - {title: "1nd Place", image: "prize-1.jpg", info: "Hak5 WiFi Pineapple"}
 - {title: "3nd Place", image: "prize-3.jpg", info: "Hak5 Packet Squirrle"}

# Hackathon Location Block
# hackathonLocationBlockTitle: "Location"
# hackathonLocationName: "Communa"
# hackathonLocationLink: "http://communa.net.ua/"
# hackathonStreetAddress: "1 Halytska St"
# hackathonAddressLocality: "Lviv"
# hackathonAddressLocalityRegion: "Lvivska"
# hackathonPostalCode: "79000"
# hackathonAddressCountry: "Ukraine"
# hackathonTimeTitle: "Hack through"
# hackathonStartTime: "2014-10-24T10:00"
# hackathonDoorTime: "09:00"
# hackathonEndTime: "2014-10-25T00:00"
# viewOnMap: "View on Google Maps"
# hackathonPlaceCoordinates: "49.840999, 24.031144"
# hackathonMapCenterCoordinates: "49.840696, 24.028754"
# hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
