# Plugins
plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME', 'Original Assets']


# Site Settings
title: "SwiftFest 2018"
email: "g@swiftfest.io"
description: "The most community driven Swift conference!"
baseurl: "/swiftfest-site"
url: "swiftfest.io"
googleAnalyticsTrackingId: "UA-43643469-5" # TODO
googleAnalyticsSiteUrl: "gdg-x.github.io" # TODO
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no" # TODO

# Organizer Info
organizerName: "Giorgio Natili"
organizerAlternateName: "Google Developer Group Lviv" # TODO
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion." # TODO
organizerEmail: "g@swiftfest.io"
organizerLogo: "/img/seo/organizer-logo.png" # TODO
organizerLink: "http://swiftfest.io"

# Head
metaKeywords: "event, swiftfest, boston, programming, swift, apple, ios, macos, tvos, watchos, developers"
twitterAccount: "@theSwiftFest"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://docs.google.com/forms/u/1/d/e/1FAIpQLSffougjfUt4bjecHeKWMgvhbiUBryAN-sU9irHQ-Ytdyih0Og/viewform"
c4sponsorsUrl: "mailto:g@swiftfest.io" # TODO: add page for sponsor application?


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Logistics"}
bottomNavigationLinks:
 - {link: "https://docs.google.com/forms/u/1/d/e/1FAIpQLSffougjfUt4bjecHeKWMgvhbiUBryAN-sU9irHQ-Ytdyih0Og/viewform", text: "Become a speaker"}
rightNavigationButtons:
 - {link: "https://docs.google.com/forms/u/1/d/e/1FAIpQLSffougjfUt4bjecHeKWMgvhbiUBryAN-sU9irHQ-Ytdyih0Og/viewform", text: "Become a speaker"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "SwiftFest <typeout> 2018" # TODO: typeout?
eventDate: "June 18–19, 2018"
typeoutTextValues: '"", "Boston", "Community", "Beantown"'
typeoutFallback: "Boston"
heroButtons:
 - {link: "https://docs.google.com/forms/u/1/d/e/1FAIpQLSffougjfUt4bjecHeKWMgvhbiUBryAN-sU9irHQ-Ytdyih0Og/viewform", text: "Become a speaker"}
 - {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "About SwiftFest"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "<p><strong>SwiftFest</strong> is a different way to experience <strong>iOS development</strong> that brings together engineers, architects, midnight coders, students, etc. in a highly social and vibrant environment entirely focused on <strong>Swift</strong>. The most community-driven Swift conference is happening for the first time in <strong>Boston</strong> – <strong>June 18–19</strong>, 2018.</p>" }
 - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favorite technology!" } # TODO: better description of workshops? Or delete section?

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "300", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Swift"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from Boston and beyond"}
 - {count: "2", specialCharacter: "", info: "parallel tracks", detail: "catch the videos later!"} #TODO: tagline appropriate?

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Featured Speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Conference Hall"
eventLocationLink: "https://www.huntingtontheatre.org/about/venue/pavilion/"
eventStreetAddress: "Calderwood Pavilion<br />527 Tremont Street"
eventAddressLocality: "Boston"
eventAddressLocalityRegion: "MA"
eventPostalCode: "02116"
eventAddressCountry: "USA"
eventStartTime: "2018-6-18T10:00"
eventDoorTime: "09:00"
eventEndTime: "2018-6-19T20:00"
eventPlaceCoordinates: "42.344797, -71.070950"
mapCenterCoordinates: "42.344848, -71.072060"
mapMobileCenterCoordinates: "42.344848, -71.072060"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Calderwood Pavillion"
venueFeatures: ["2 full theatrical stages", "Seating for 370", "Located in downtown Boston"]

# Tweets Feed Block
# TODO: need to set up tweetledee or delete this section https://github.com/tweetledee/tweetledee
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "swiftfest"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
# TODO: add form for mailing list
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Find out about new speaker announcements and other SwiftFest news."

# Tickets Block
ticketsTitle: "Tickets"
ticketsInfo: "Conference ticket purchase includes 2 full days of sessions (June 18th–19th) and exhibitor booths, a ticket to the official conference party on June 18th for you and a guest, morning snack, lunch, and afternoon snack on both days."
ticketsOffers:
 -
  name: "Super Early Bird"
  price: "299"
  priceCurrency: "USD"
  ticketsNumber: "150" # TODO: number?
  ribbon: "-5%" # TODO: percent?
  buyButtonLink: "https://www.eventbrite.com/e/swiftfest-2018-tickets-37370599469#tickets"
  buyButtonText: "Buy Now"
  ticketContentList: ["2 full days of sessions", "Exhibitor booths", "Conference party & meals"]
  validFrom: "2018-7-18T10:00"
  validThrough: "2018-07-25T23:59"
  soldOut: false
  disabled: false
 -
  name: "Last Chance"
  price: "349" # TODO: price?
  priceCurrency: "USD"
  ticketsNumber: "100" # TODO: number
  ribbon: "-20%"
  featured: true
  buyButtonLink: "https://www.eventbrite.com/e/swiftfest-2018-tickets-37370599469#tickets"
  buyButtonText: "Buy Now"
  ticketContentList: ["2 full days of sessions", "Exhibitor booths", "Conference party & meals"]
  validFrom: "2018-7-18T10:00"
  validThrough: "2018-07-25T23:59"
  soldOut: false
  disabled: false
 -
  name: "Student"
  price: "99"
  priceCurrency: "USD"
  ticketsNumber: "50" # TODO: number
  buyButtonLink: "https://www.eventbrite.com/e/swiftfest-2018-tickets-37370599469#tickets"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund" # TODO: rules?
  ticketContentList: ["2 full days of sessions", "Exhibitor booths", "Conference party & meals"]
  validFrom: "2018-7-18T10:00"
  validThrough: "2018-07-25T23:59"
  soldOut: false
  disabled: false
  soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://twitter.com/intent/user?screen_name=TheSwiftFest", icon: "twitter"}
 - {link: "https://www.facebook.com/theSwiftFest", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Contacts"
  links:
   - {link: "mailto:g@swiftfest.io", text: "g@swiftfest.io"}
 -
  title: "FAQ"
  links:
   - {permalink: "/conduct/", text: "Code of Conduct"}

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "SwiftFest is put on by a group of passionate community builders in Boston." # TODO: write better blurb

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "40.046741, -79.244695"
logisticsMapMobileCenterCoordinates: "42.412080, -71.733608"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Boston"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'} # TODO: real directions
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'} # TODO: real directions
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'} # TODO: real hotel info
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"} # TODO: list real hotels
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"} # TODO: list some stuff here
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"} # TODO: what even goes here?
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
