# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']

# Site Settings
title: "Agile Pays Basque"
email: "agilepb@gmail.com"
description: "Agile Pays Basque les 21 et 22 Septembre 2018 à Bidart. Venez découvrir, échanger, apprendre, expérimenter, tester, approfondir vos connaissances, ou simplement discuter autour de l’agilité et du lean."
baseurl: "/site-web"
url: "https://agilepaysbasquedev.github.io"
permalink: "/blog/:title"

# FIXME Google Analytics
googleAnalyticsTrackingId: "UA-101197587-1"
googleAnalyticsSiteUrl: "agilepaysbasque.github.io/site-web/"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "Agile Pays Basque"
organizerAlternateName: "Agile Pays Basque"
organizerDescription: "Association pour promouvoir l'Agilité au sein du Pays Basque et ses alentours. Informer et initier aux méthodes agiles."
organizerEmail: "agilepb@gmail.com"

# FIXME logo
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://agile-paysbasque.fr"

# Head
metaKeywords: "Agile, Scrum, KanBan, DevOps, Lean Startup, Lean,"
twitterAccount: "@agilepb"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# FIXME Sponsorhip PDF
# XXX relative url must start with "/" here. Others sponsor relative links don't need it'
c4sponsorsUrl: "/blog/devenir-sponsor"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Accueil"}
 - {permalink: "/cfp/", text: "Devenir Orateur", }
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "2017"}
 - {permalink: "/schedule2016/", text: "2016"}
 - {permalink: "/team/", text: "Equipe"}
# - {permalink: "/logistics/", text: "S'y rendre 2017"}
# - {permalink: "/speakers/", text: "Orateurs 2017"}
# - {permalink: "/sponsors/", text: "Sponsors 2017"}
bottomNavigationLinks:
 - {permalink: "/#tickets", text: "Acheter un billet"}
rightNavigationButtons:
 - {permalink: "/#tickets", text: "Acheter un billet"}

# Hero Block
heroImage: "hero"
heroTitle: "Agile <typeout> 2018"
eventDate: "21 / 22 Septembre 2018"
typeoutTextValues: '"", "Pays Basque", "Cote Basque"'
typeoutFallback: "Pays Basque"
heroButtons:
 - {permalink: "/cfp/", text: "Devenir Orateur"}
heroCount: 8
heroFirst: 1

# About Block
aboutTitle: "3ème édition de la conférence Agile Pays Basque"
aboutLines:
 - {text: "L'agilité avec l'ensemble de ses valeurs, principes, méthodes et pratiques, se diffuse progressivement dans nos environnements de travail et dans l'enseignement."}
 - {text: "La 3ème édition : Agile Pays Basque 2018, sera cette année l'évènement agile du Pays Basque. C'est le rendez-vous des professionnels, enseignants et étudiants qui souhaitent savoir comment s'y prendre, découvrir, échanger, apprendre, expérimenter, tester, approfondir leurs connaissances, ou simplement discuter autour de l’agilité."}
 - {text: "Débutants ou experts, curieux ou praticiens, venez donc partager, échanger, vous enrichir sur des thématiques telles que Management Agile, Développement logiciel, Lean IT, Lean Startup, Scrum, Kanban, eXtreme Programming, et l'agile hors IT."}

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "200", specialCharacter: "", info: "Participants attendus", detail: "Professionnels, Enseignants, &Eacute;tudiants ou Curieux"}
 - {count: "48", specialCharacter: "", info: "Heures d'échanges", detail: "Autour de l'agilité pour tout niveau"}
 - {count: "20", specialCharacter: "+", info: "Sessions", detail: "Pour tout type de profil"}
 - {count: "3", specialCharacter: "", info: "Formats différents", detail: "Conférences, Ateliers, Forums Ouverts"}

# Format Block
formatBlock:
 - {title: "19 Conférences", image: "conference.jpg", text: "réparties sur 3 thématiques \"Culture Agile et Management\", \"Découverte et Conception de Produits\" et \"Développement Logiciel et Tests\". Débutants bienvenus!" }
 - {title: "5 Ateliers", image: "workshop.jpg", text: "pour découvrir ou d'approfondir des pratiques agiles en lien avec les thématiques des conférences" }
 - {title: "1 Forum ouvert", image: "forum.jpg", text: "pendant 1 journée avec un programme co-construit le jour même entre les speakers et les participants, pour augmenter la variété des thématiques ou les approfondir" }

# Latest News Block
latestNewsTitle: "Dernières news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstars"
rockstarSpeakersButtonText: "Voir tous les orateurs"

# Location Block
locationBlockTitle: "Pour s'y rendre'"

eventLocationName: "ESTIA"
eventLocationLink: "http://www.estia.fr/"
eventStreetAddress: "92, allée Théodore Monod"
eventAddressLocality: "Bidart"
eventAddressLocalityRegion: "64"
eventPostalCode: "64210"
eventAddressCountry: "France"
eventStartTime: "2018-09-21T09:00"
eventDoorTime: "09:00"
eventEndTime: "2018-09-21T18:00"
eventPlaceCoordinates: "43.446321, -1.553914"

event2LocationName: "A définir"
event2LocationLink: "https://www.google.fr/maps"
event2StreetAddress: ""
event2AddressLocality: ""
event2AddressLocalityRegion: "64"
event2PostalCode: ""
event2AddressCountry: "France"
event2StartTime: "2018-09-22T09:00"
event2DoorTime: "09:00"
event2EndTime: "2018-09-22T18:00"
event2PlaceCoordinates: "43.521377, -1.523359"

mapCenterCoordinates: "43.445995, -1.553750"
mapMobileCenterCoordinates: "43.445995, -1.553750"



# Venue Block
venueBlockTitle: "2 jours sur 2 lieux différents"
venueBigImage: "venue_0.jpg"
# ESTIA
venueSmallImage1: "venue_1.jpg"
venueTitle: "ESTIA"
venueFeatures: ["Ecole d'ingénieurs", "Technopole Izarbel", "64210 BIDART"]
# Atlanthal
venue2Title: "A Définir"
venue2Features: ["", "", ""]
venueSmallImage2: "venue_2.jpg"

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "Quoi de neuf ?"
twitterHashTag: "AgilePaysBasque"
twitterFeed: ""

# Partners Block
organizersTitle: "Organisé par"
partnersTitle: "Partenaires (2017)"
partnersC4sponsorsButton: "Devenir Sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "S'abonner aux infos"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "L'inscription est ouvert à partir de Juin. Le nombre de place est limité. Restez à l'écoute!"

# Tickets Block
ticketsTitle: "Billetterie"
ticketsInfo: "Les billets donnent access à toutes les conferences, pauses café. Les repas sont en option. L'hébergement n'est PAS inclus dans le prix du billet."
ticketsBgImage: "tickets.jpg"
ticketsOffers:
 -
  name: "\"Earl Bird\"<br/>2J, Billet+Repas"
  price: "50"
  priceCurrency: "€"
  ticketsNumber: "70"
  ribbon: "-35%"
  buyButtonLink: "https://www.helloasso.com/associations/agile-cote-basque/evenements/agile-pays-basque-2017/"
  buyButtonText: "Acheter"
  ticketContentList: ["Conférences et ateliers à l'ESTIA, vendredi", "Repas au Spot' vendredi midi", "Forum ouvert à l'ATLANTHAL, samedi", "Repas à l'ATLANTHAL, samedi midi"]
  validFrom: "2017-06-14T00:00"
  validThrough: "2017-07-14T23:59"
  disabled: false  
 -
  name: "Vendredi<br/>(Billet)"
  price: "35"
  priceCurrency: "€"
  ticketsNumber: "70"
  ribbon: ""
  buyButtonLink: "https://www.helloasso.com/associations/agile-cote-basque/evenements/agile-pays-basque-2017/"
  buyButtonText: "Acheter"
  ticketContentList: ["Conférences et ateliers à l'ESTIA, vendredi", "<br/>&nbsp;", "<br/>&nbsp;", "<br/>&nbsp;"]
  validFrom: "2017-06-14T00:00"
  validThrough: "2017-09-21T23:59"
  disabled: false
 -
  name: "Vendredi<br/>(Repas)"
  price: "10"
  priceCurrency: "€"
  ticketsNumber: "70"
  ribbon: ""
  buyButtonLink: "https://www.helloasso.com/associations/agile-cote-basque/evenements/agile-pays-basque-2017/"
  buyButtonText: "Acheter"
  ticketContentList: ["<br/>&nbsp;", "Repas au Spot' vendredi midi", "<br/>&nbsp;", "<br/>&nbsp;"]
  validFrom: "2017-06-14T00:00"
  validThrough: "2017-09-21T23:59"
  disabled: false
 -
  name: "Samedi<br/>(Billet+Repas)"
  price: "30"
  priceCurrency: "€"
  ticketsNumber: "40"
  ribbon: ""
  buyButtonLink: "https://www.helloasso.com/associations/agile-cote-basque/evenements/agile-pays-basque-2017/"
  buyButtonText: "Acheter"
  ticketContentList: ["<br/>&nbsp;", "<br/>&nbsp;", "Forum ouvert à l'ATLANTHAL, samedi", "Repas à l'ATLANTHAL, samedi midi"]
  validFrom: "2017-06-14T00:00"
  validThrough: "2017-09-21T23:59"
  disabled: false
  #-
  #name: "Etudiant"
  #price: "XX"
  #priceCurrency: "€"
  #ticketsNumber: "50"
  #buyButtonLink: "http://dfua.ticketforevent.com/"
  #buyButtonText: "Acheter"
  #additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  #ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  #validFrom: "2014-08-20T10:00"
  #validThrough: "2014-10-23T23:59"
  #soldOut: true
  #soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://twitter.com/intent/user?screen_name=agilepb", icon: "twitter"}
 - {link: "https://www.facebook.com/AgilePaysBasque", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Liens"
  links:
   - {link: "https://www.meetup.com/fr-FR/Agile-Pays-Basque/", text: "Meetups"}
   - {link: "https://agile-paysbasque.slack.com/", text: "Slack"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:agilepb@gmail.com", text: "agilepb@gmail.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code de Conduite"}

# Blog
blogTitle: "Dernières news"
blogCommentsEnabled: false
discusShortName: "agilepaysbasque"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "Envie de participer ?"
aboutUs: ""

# CFP Block
cfpBlockTitle: "Appel à orateurs 2018"

# Logistics Find Way Block
findWayTitle: ""
findWayDistance: "Distance"
findWayDriving: "EN VOITURE"
findWayWalking: "A PIED"
findWayBicycling: "A VELO"
findWayTransit: "TRANSPORTS"
findWayFindFlight: "Trouver un Vol"
logisticsMapCenterCoordinates: "43.446264, -1.553900"
logisticsMapMobileCenterCoordinates: "43.446264, -1.553900"
logisticsMapAutoDirections: true

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Autour de l'ESTIA"
directionDetailsCards:
 - {title: "Train et aéroport", information: "La gare TGV Biarritz (La Negresse) est située à 5 minutes. <p>L'aéroport Biarritz (Parme) est situé à 10 minutes.</p>"}
 - {title: "Par bus", information: "La technopole Izarbel, et donc l'Estia, est desservie par Chronoplus le réseau de transport de l’agglomération Côte Basque Adour. <p>La ligne C vous permet d'attendre l'ESTIA. Tous les arrêts de la ligne C sur le site web. Consultez vos trajets et vos horaires en un seul clic sur internet <a href='http://www.chronoplus.eu/horaires_ligne/?rub_code=6&lign_id=4'>www.chronoplus.eu</a> et même depuis votre mobile sur www.chronoplus.mobi.</p>"}
 - {title: "Par autoroute", information: "<p><b>Depuis Bordeaux</b></p><p>Autoroute A63, sortie n° 4 : Biarritz Parme à 2 minutes.</p><p><b>Depuis Toulouse</b></p><p>Autoroute A64 jusqu'à Bayonne puis A63 (direction Espagne), sortie n° 4 : Biarritz Parme à 2 minutes</p>"}
directionDetailsWideCards:
 -
  title: "Questions ?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "http://www.fasthotel.com/aquitaine/hotels-biarritz-pas-cher", text: "Fast Hotel"}
     - {link: "http://www.atlanthal.com/", text: "Athlantal"}
   -
    title: "Restauration"
    links:
     - {link: "http://www.le-spot.rest", text: "Le Spot"}
     - {link: "http://www.fasthotel.com/aquitaine/hotels-biarritz-pas-cher", text: "Fast Hotel"}

# Logistics Direction Details Block
findWayTitle2: ""
directionDetails2Image: "direction-details-2.jpg"
directionDetails2Title: "Autour d'Atlanthal"
directionDetails2Cards:
 - {title: "Par autoroute", information: "<p><b>Depuis Bordeaux</b> Autoroute A63 en direction de Bayonne.</p><p>Prendre la sortie 6 : Bayonne-Nord. Continuer sur D810. Prendre Avenue Marcel Dassault et Avenue de l'Adour en direction de Boulevard des Plages à Anglet.</p><p><b>Depuis Toulouse</b> Autoroute A64 jusqu'à Bayonne puis Autoroute A63 (direction Bordeaux), sortie n° 6 : Bayonne-Nord. Continuer sur D810. Prendre Avenue Marcel Dassault et Avenue de l'Adour en direction de Boulevard des Plages à Anglet.</p>"}
 - {title: "Par bus", information: "<p>Atlantal est desservi par Chronoplus le réseau de transport de l’agglomération Côte Basque Adour.</p><p>La ligne 10 vous permet d'atteindre l'hôtel. Depuis Bayonne ou Biarritz : Ligne 10 (itinéraire) : Bayonne Technocité – Gare de Biarritz (correspondances) – Anglet Chambre d'Amour – Anglet Les Cavaliers.</p><p>Tous les arrêts de la ligne 10 sur le <a href='http://www.chronoplus.eu/horaires_ligne/?rub_code=6&lign_id=1'>site web</a>.</p><p>Consultez vos trajets et vos horaires en un seul clic sur internet <a href='www.chronoplus.eu'>Chronoplus</a> et même depuis votre mobile sur <a href='www.chronoplus.mobi'>Chronoplus Mobile</a></p>"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: false

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "Voir sur Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
