# Plugins
plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "WABF25"
email: "wabf-info@wharton.upenn.edu"
description: "The premier and longest running student-organized business conference focused on Africa."
#baseurl: "/wabf25"
baseurl: ""
url: "https://nickolson.github.io"
permalink: "/blog/:title"
#googleAnalyticsTrackingId: "UA-43643469-5"
#googleAnalyticsSiteUrl: "nickolson.github.io"
#siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "Wharton Africa Business Forum"
organizerAlternateName: "Wharton Africa Business Forum"
organizerDescription: "A Wharton student organization"
organizerEmail: "wabf-info@wharton.upenn.edu"
#organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://whartonafrica.com"

# Head
metaKeywords: "Wharton, conference, Africa, business, Philadelphia, student"
twitterAccount: "@wabf25"
 # socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://goo.gl/forms/1lL8gHN106JdFNKX2"
c4sponsorsUrl: "mailto:yolandak@wharton.upenn.edu?Subject=WABF Sponsorship"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 # - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Logistics"}
 - {permalink: "/venturecomp/", text: "Venture Competition"}
 -
   subText: "Prior Years"
   links:
     - {link: "http://wabf2016.whartonafrica.com", text: "WABF 2016"}
     - {link: "http://wabf2015.whartonafrica.com", text: "WABF 2015"}
     - {link: "http://wabf2014.whartonafrica.com", text: "WABF 2014"}
     - {link: "http://wabf2013.whartonafrica.com", text: "WABF 2013"}
bottomNavigationLinks:
 - {link: "https://wabf.ticketspice.com/wharton-africa-business-forum", text: "Register to Attend"}
rightNavigationButtons:
 - {link: "https://wabf.ticketspice.com/wharton-africa-business-forum", text: "Register to Attend"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Wharton Africa Business Forum <typeout>"
eventLocation: "Philadelphia, PA"
eventDate: "November 3 - 5, 2017"
typeoutTextValues: '"", "25", "2017", "#WABF25"'
typeoutFallback: "25"
heroButtons:
 #- {link: "https://goo.gl/forms/1lL8gHN106JdFNKX2", text: "Become a speaker"}
 - {link: "https://wabf.ticketspice.com/wharton-africa-business-forum", text: "Buy tickets"}

# About Block
aboutTitle: "About WABF"
aboutBlock:
 - {title: "Conference", image: "panels.jpg", text: "A full day of engaging panels with interesting speakers." }
 - {title: "Networking", image: "networking.jpg", text: "Multiple opportunities to network and meet others with an interest in business in Africa." }
 - {title: "Venture Competition", image: "venturecomp.jpg", text: "Come join the WABF Venture Competition and see the next generation of entrepreneurs pitch their ideas." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "500", specialCharacter: "+", info: "attendees", detail: "from Africa and beyond"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of engaging programming"}
 - {count: "12", specialCharacter: "+", info: "panels", detail: "covering a variety of subjects"}
 - {count: "4", specialCharacter: "", info: "keynotes", detail: "by prominent speakers"}

# Latest News Block
latestNewsTitle: "Latest News"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Loews Hotel Philadelphia"
eventLocationLink: "https://www.loewshotels.com/philadelphia-hotel"
eventStreetAddress: "1200 Market St."
eventAddressLocality: "Philadelphia"
eventAddressLocalityRegion: "Pennsylvania"
eventPostalCode: "19107"
eventAddressCountry: "USA"
eventStartTime: "2017-11-03T14:00"
eventDoorTime: "14:00"
eventEndTime: "2017-11-05T14:00"
eventPlaceCoordinates: "39.9518, -75.1603"
mapCenterCoordinates: "39.952497, -75.163725"
mapMobileCenterCoordinates: "39.952497, -75.163725"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
#venueSmallImage3: "venue_3.jpg"
venueTitle: "3 Amazing Venues"
venueFeatures: ["Loews Hotel Philadelphia", "Spirit of Philadelphia", "Marriott Hotel Philadelphia"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "wabf25"
#twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
 # organizersTitle: "Organizers"
partnersTitle: "Sponsors"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://whartonafrica.us7.list-manage.com/subscribe/post?u=a7c01efb918a8f43dfa398611&amp;id=9135c1b93f"
subscribeInfo: "Sign up to stay in the loop with all our updates."

# Tickets Block
ticketsTitle: "Ticket Options"
#ticketsInfo: "A limited number of discounted tickets will be available for select groups (e.g., students, alumni, YAM)."
ticketsOffers:
 -
  name: "The Classic Package"
  price: "250"
  priceCurrency: "USD"
  #ticketsNumber: "300"
  ribbon: "-25%"
  buyButtonLink: "https://wabf.ticketspice.com/wharton-africa-business-forum"
  buyButtonText: "Buy Now"
  additionalInfo: "Conference + Career Fair + Gala + Conference Afterparty"
  #ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2017-09-15T10:00"
  validThrough: "2017-11-03T12:00"
  disabled: false
 -
  name: "The Conference"
  price: "150"
  priceCurrency: "USD"
  #ticketsNumber: "100"
  ribbon: "-25%"
  #featured: true
  buyButtonLink: "https://wabf.ticketspice.com/wharton-africa-business-forum"
  buyButtonText: "Buy Now"
  additionalInfo: "Provides access to Friday and Saturday keynotes, industry breakout panels and prospective student events, New Venture Competition, and flagship Career Fair."
  #ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2017-09-15T10:00"
  validThrough: "2017-11-03T12:00"
  disabled: false
 -
  name: "The Gala"
  price: "100"
  priceCurrency: "USD"
  #ticketsNumber: "100"
  buyButtonLink: "https://wabf.ticketspice.com/wharton-africa-business-forum"
  buyButtonText: "Buy Now"
  additionalInfo: "Landmark black-tie cocktails, seated dinner, and Closing Keynote."
  #ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2017-09-15T10:00"
  validThrough: "2017-11-03T12:00"
  #soldOut: true
  #soldOutText: "Sold Out"
  disabled: false
 -
  name: "The Afterparty"
  price: "75"
  priceCurrency: "USD"
  #ticketsNumber: "250"
  ribbon: "-25%"
  #featured: true
  buyButtonLink: "https://wabf.ticketspice.com/wharton-africa-business-forum"
  buyButtonText: "Buy Now"
  additionalInfo: "Saturday Conference Afterparty headlined by private concert by top-billing performing artist."
  #ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2017-09-15T10:00"
  validThrough: "2017-11-03T12:00"
  disabled: false
 -
  name: "Friday Mixer"
  price: "15"
  priceCurrency: "USD"
  #ticketsNumber: "250"
  ribbon: "-25%"
  #featured: true
  buyButtonLink: "https://wabf.ticketspice.com/wharton-africa-business-forum"
  buyButtonText: "Buy Now"
  additionalInfo: "The 1925 Lounge - tickets valid until 11:30pm."
  #ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2017-09-15T10:00"
  validThrough: "2017-11-03T12:00"
  disabled: false
 -
  name: "Sunday Young African MBA (YAM) Brunch"
  price: "30"
  priceCurrency: "USD"
  #ticketsNumber: "250"
  ribbon: "-25%"
  #featured: true
  buyButtonLink: "https://wabf.ticketspice.com/wharton-africa-business-forum"
  buyButtonText: "Buy Now"
  additionalInfo: "Join Young African MBAs for their annual brunch to bookend the WABF weekend."
  #ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2017-09-15T10:00"
  validThrough: "2017-11-03T12:00"
  disabled: false
 -
  name: "Sunday Wharton Alumni Brunch"
  price: "20"
  priceCurrency: "USD"
  #ticketsNumber: "250"
  ribbon: "-25%"
  #featured: true
  buyButtonLink: "https://wabf.ticketspice.com/wharton-africa-business-forum"
  buyButtonText: "Buy Now"
  additionalInfo: "This event is open to Wharton Alumni. Registration required."
  #ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2017-09-15T10:00"
  validThrough: "2017-11-03T12:00"
  disabled: false

# Footer
socialLinks:
 #- {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://twitter.com/wabf__25", icon: "twitter"}
 #- {link: "https://facebook.com/GDGLviv", icon: "facebook"}
 #- {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://whartonafrica.com", text: "Wharton Africa Students Association"}
   # - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:wabf-info@wharton.upenn.edu", text: "wabf-info@wharton.upenn.edu"}
 -
  # title: "FAQ"
  # links:
  # - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: false
discusShortName: "devfestua"

# Speakers List Block
showSessions: false

# Team Block
teamBlockTitle: "About us"
aboutUs: "We are a team of Wharton and UPenn students who hail from across the continent. We're interested in all things business in Africa."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "39.9524, -75.1637"
logisticsMapMobileCenterCoordinates: "39.9524, -75.1637"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Philadelphia"
directionDetailsCards:
 - {title: "From the Airport", information: 'Philadelphia International Airport is only 7 miles from downtown Philly and it is easily reachable by car, public transport or taxi. More information is available from the <a href="https://https://www.phl.org/">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Philly so you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Philadelphia.'}
 - {title: "Hotels", information: 'Philly has lots of great hotels and hostels. More information will be available later.'}
#directionDetailsWideCards:
# -
#  title: "Questions?"
#  subCards:
#   -
#    title: "Hotels"
#    links:
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#   -
#    title: "Registration"
#    links:
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#   -
#    title: "Attendance Details"
#    links:
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Venture Competion
hackathonTitle: "Hackathon"
enableHackathon: true

# Venture Competition About Block
aboutHackathonTitle: "Pitch your startup"
hackathonRows:
 - {title: "What is it?", details: "At WABF25, we aim to connect promising early-stage African entrepreneurs to a powerful network of investors, mentors, and coaches to accelerate their growth, and provide them with resources they can use to develop into regional powerhouses.<br><br>As part of this initiative, the Wharton African Student Association is pleased to announce <strong>the 4th Annual Venture Competition</strong> at this yearâ€™s conference. Contestants will submit an application outlining their start-up or idea, and we will select finalists to pitch to an experienced panel of judges and the audience at the conference.<br><br>If you believe that your idea has what it takes, please read through the eligibility details below. The application deadline is <strong>October 13, 2017 11:59 EST</strong>"}
 - {title: "Eligibility Criteria?", details: "<ul><li>Must be Africa-focused<li>Can be for-profit, non-profit, or social enterprise<li>Less than 5 years of operations<li>Less than $750,000 raised to date in external funding</li></us>"}
 - {title: "What are the prizes?", details: "Finalists gain...<ul><li>An opportunity to present in front of top Africa-focused VCs and leading minds in entrepreneurship<li>Invaluable feedback from a panel of experienced judges<li>An opportunity to participate in the Startup Fair<li>An opportunity to network with others interested in African entrepreneurship</li></us><br><p><strong>...and the grand prize winner will receive $10,000 in no-equity cash for their venture</strong></p>"}
 - {title: "What is the Startup Fair?", details: "The Startup Fair is an exclusive event for the top businesses that applied for the 2017 Wharton Africa Business Forum Venture Competition. Each participant will be given a booth to showcase their business. This event will serve as an opportunity to market your business, recruit talent, and connect with potential investors."}
 - {title: "Submission Instructions", details: "<ul><li>Deadline of Friday, October 13th, 11:59PM EST<li>5 page (maximum) PowerPoint presentation. This must include 1 page on the leadership team. There is no limit for the appendix which can be referred to during Q&A<li>PowerPoint presentation must highlight problem and solution proposed, and must demonstrate unique competitive advantage and potential for significant growth in the next five years</li></ul>"}
 - {title: "Competition Logistics", details: "<ul><li>Finalists will be notified by October 18th<li>At the conference, each contestant will present for 5 minutes, followed by 5 minutes for Question + Answer from the judges<li>Judges will select one winner for the grand prize</li></ul>"}

# Venture Competition button
vcButton:
  - {link: "https://goo.gl/forms/M07G93qI8gYtecfA3", text: "Apply for the Venture Competition"}

# Venture Competition Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Venture Competition Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "Grand Prize", info: "$10,000 of funding for your venture"}
 #- {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 #- {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Venture Competition Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Loews Hotel Philadelphia"
hackathonLocationLink: "https://www.loewshotels.com/philadelphia-hotel"
hackathonStreetAddress: "1200 Market St"
hackathonAddressLocality: "Philadelphia"
hackathonAddressLocalityRegion: "PA"
hackathonPostalCode: "19107"
hackathonAddressCountry: "USA"
hackathonTimeTitle: "Pitches from"
hackathonStartTime: "2017-11-03T15:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2017-11-03T18:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "39.9518, -75.1603"
hackathonMapCenterCoordinates: "39.952497, -75.163725"
hackathonMapMobileCenterCoordinates: "39.952497, -75.163725"

# Venture Competition FAQs
aboutVentureCompFAQsTitle: "FAQ"
faqRows:
 - {question: "What are the judging criteria?", answer: "<ul><li>Product/Service<li>Management Team<li>Market Opportunity<li>Competitive Edge<li>Risk/Reward<li>Financial/Feasibility<li>Impact</li></ul>"}
 - {question: "Can I include a video?", answer: "Sure, absolutely!"}
 - {question: "When will you notify finalists?", answer: "Finalists will be notified within a week of the application deadline"}
 - {question: "Will the WABF Team help prepare contestants for the pitch?", answer: "Yes, we will have another conference call session for each contestant before the competition"}
 - {question: "Does it cost money to participate?", answer: "WABF Team will not charge anything from contestants, but you will be responsible for travel to the competition"}
 - {question: "Any other questions?", answer: "Please contact us here (wabfventurecompetition@gmail.com)", contactus: "mailto:wabfventurecompetition@gmail.com?Subject=WABF%20Venture%20Competition%20Question"}
 - {answer: "We reserve the right to disqualify any team that misrepresents any internal or external data in its application"}
