# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "BSides Halifax Quarantine Edition"
email: "info@halifaxbsides.ca"
description: "BSides is a community-driven framework for building events for and by information security community members."
baseurl: ""
url: "https://halifaxbsides.ca"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-165605284-1"
googleAnalyticsSiteUrl: "gdg-x.github.io"
siteVerification: "U2vM0e028DKxBzX3zvCNmR2ZQk31oXU5asShWbU3Oqg"

# Organizer Info
organizerName: "BSides Halifax"
organizerAlternateName: "Halifax BSides"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Cyber Security with passion."
organizerEmail: "info@halifaxbsides.ca"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://halifaxbsides.ca"

# Head
metaKeywords: "event, BSides, Halifax, Cyber, Security, infosec"
twitterAccount: "@HalifaxBSides"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4sponsorsUrl: "/assets/BSides_HFX_Sponsorship_Kit.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "https://forms.gle/Wpa65azBiQy5NGrG6", text: "Call for Papers"}
 #- {permalink: "/schedule/", text: "Schedule"}
 #- {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
 #- {permalink: "/hackathon/", text: "Hackathon"}
 - {permalink: "/2021", text: "Last Years Event"}
bottomNavigationLinks:
- {link: "/assets/BSides_HFX_Sponsorship_Kit.pdf", text: "Become a sponsor"}

# Hero Block
heroImage: "halifax.jpg"
heroTitle: "BSides Halifax 2023"
eventDate: "may 4th, 2023"
typeoutTextValues: '"now with more pants", "IRL", "now in 3D"'
typeoutFallback: ""
   #heroButtons:
   #- {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "About BSides Halifax"
aboutBlock:
 - {
    title: "Conference",
    image: "conference.jpg",
    text: "Physical security is an essential part of overall security, and we've thoroughly enjoyed hosting virtual versions of BSides Halifax over the last few years. This year, BSides Halifax will be held at the Halifax Central Library, on May the 4th, 2023.
<br /><br />I'll give you a moment to get the jokes out of your system.
<br /><br />All good? Good. We're looking for your best talks about all aspects of security - blue team, red team, purple team, social engineering, that new tool you think everyone should know about, we want to hear about anything and everything you want to talk about.
<br /><br />We especially want to hear from underrepresented groups, on account of them being, you know, underrepresented. Studies show that specifically calling out folks who don't think a security conference is for them increases their likelihood of applying, so consider this your official \"This conference is for you!\" invitation.
<br /><br />Our CFP link can be found here: (link), the deadline is (deadline).
<br /><br />Tickets will be very limited this year and are available for a minimum \"donation\" of $13.37 (see what we did there). All proceeds go to Feed Nova Scotia, because have you seen grocery prices lately?
<br /><br />
We look forward to seeing you in May!"
}

## Statistic Block
#statisticBlockImage: "statistic.jpg"
#statisticBlock:
#- {count: "4", specialCharacter: "+", info: "hours", detail: "of amazing talks"}
#- {count: "8", specialCharacter: "", info: "speakers", detail: "from across North America"}
#- {count: "24", specialCharacter: "", info: "hour", detail: "secure coding challange"}

## Rockstar Speakers Block
#rockstarSpeakersImage: "rockstar-speakers.jpg"
#rockstarSpeakersCount: 3
#rockstarSpeakersTitle: "Rockstar speakers"
#rockstarSpeakersButtonText: "See all speakers"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

## Tickets Block
#ticketsTitle: "Tickets"
#ticketsInfo: "All proceeds go to Feed Nova Scotia"
#ticketsOffers:
#-
 #name: "General Admittance"
 #price: "$13.37"
 #priceCurrency: "CAD"
##   ticketsNumber: "150"
##   ribbon: "-5%"
 #buyButtonLink: "https://www.eventbrite.ca/e/security-bsides-halifax-2021-virtual-tickets-154149175333"
 #buyButtonText: "Buy Now"
 #ticketContentList: ["Donations accepted", "Access to amazing talks", "Our everlasting love and admiration", "All proceeds go to Feed Nova Scotia"]
##   validFrom: "2014-08-25T10:00"
##   validThrough: "2014-09-30T23:59"

# Footer
socialLinks:
 - {link: "https://twitter.com/intent/user?screen_name=HalifaxBSides", icon: "twitter"}
 - {link: "https://discord.gg/aGzzj4B", icon: "site"}
 - {link: "https://github.com/bsideshalifax", icon: "github"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www.securitybsides.com/w/page/12194156/FrontPage", text: "Security BSides", icon: "site"}
   - {link: "https://atlseccon.com", text: "Atlantic Security Conference", icon: "site"}
   - {link: "https://dc902.ca", text: "DEFCON Halifax", icon: "site"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:info@bsideshalifax.ca", text: "info@bsideshalifax.ca", icon: "email"}
 -
  title: "Code of Conduct"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

## Speakers List Block
#showSessions: false

## Hackathon
#hackathonTitle: "Hackathon"
#enableHackathon: false

# Hackathon About Block
# aboutHackathonTitle: "CMD+CTRL"
# hackathonRows:
#    - {title: "", image: "hackathon-0.png", details: "<p>Stuck at home, but still want to test your skills in identifying web app vulnerabilities?  BSides Halifax and Security Innovation invite players to virtually compete in CMD+CTRL, a web application cyber range where players exploit their way through hundreds of vulnerabilities that lurk in business applications today.  Success means learning quickly that attack and defense is all about thinking on your feet.</p>
# <p>For each vulnerability you uncover, you are awarded points. Climb the interactive leaderboard for a chance to win fantastic prizes! CMD+CTRL is ideal for development teams to train and develop skills, but anyone involved in keeping your organizationâ€™s data secure can play - from developers and managers and even CISOs.</p>
# <p>All you need is your laptop and inner evil-doer!</p>
# <br />
# <p>Register early to reserve your spot and get a sneak peek at our cheat sheets and FAQs!</p>"}

# Hackathon Prizes Block
# prizesTitle: "Prizes"
# prizes:
#  - {title: "2nd Place", image: "prize-2.png", info: "Hak5 Bash Bunny"}
#  - {title: "1st Place", image: "prize-1.jpg", info: "Hak5 WiFi Pineapple"}
#  - {title: "3rd Place", image: "prize-3.jpg", info: "Hak5 Packet Squirrle"}
