# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
# TODO: change verification
title: "GDG DevFest Croatia 2018"
email: "devfest.croatia@gmail.com"
description: "GDG DevFest is a set of events all around the world"
baseurl: ""
url: "https://devfesthr.com"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-71034344-2"
googleAnalyticsSiteUrl: "devfesthr.com"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"
googleMapsApiKey: "AIzaSyAtzzB7A1rC3e27_lHmEB6AevYpsYmdJCU"
# Organizer Info
organizerName: "GDG Zagreb"
organizerAlternateName: "Google Developer Group Zagreb"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about technology with passion."
organizerEmail: "devfest.croatia@gmail.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://www.meetup.com/GDG-Zagreb/"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, zagreb"
twitterAccount: "@DevFest"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
# change sponsorship url
c4pUrl: "mailto:devfest.croatia@gmail.com"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 # - {permalink: "/blog/", text: "Blog"}
 # - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 # - {permalink: "/team/", text: "Team"}
 # - {permalink: "/logistics/", text: "Logistics"}
 # - {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 - {link: "mailto:devfest.croatia@gmail.com", text: "Become a speaker"}
rightNavigationButtons:
 - {permalink: "/#tickets", text: "Buy tickets"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "GDG DevFest <typeout> 2018"
eventDate: "1. December, 2018"
typeoutTextValues: '"", "Season", "Croatia"'
typeoutFallback: "Season"
heroButtons:
 - {link: "mailto:devfest.croatia@gmail.com", text: "Become a speaker"}
 - {permalink: "/#tickets", text: "Buy tickets"}
 - {link: "/GDG_DevFest_Croatia_2018_Partnership_Proposition.pdf", text: "Sponsor us"}
# About Block
aboutTitle: "About GDG DevFest"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "GDG DevFest brings together the world class experts in Android, Web and Cloud technologies to Zagreb, Croatia!<br>
• Google Developer Experts - Speakers and Mentors<br>
• Talks and Seasons<br>
• Show and tell booths with the best tech companies in Croatia<br>
• Job speed dating<br>
<br>
...a day full of tech surprises!<br>
<br>
Google tech conference organized and brought to Croatia by GDG Zagreb & Women Techmakers Croatia.
" }
 - {title: "Show and tell", image: "hackathon.jpg", text: "Show off your projects, tell your story, see what others are working on!<br>
Lobby full of companies and startups showing off their work in awesome HUB385!<br>
Look, mingle, learn, try and be impressed by some of the best technology innovations around!" }
 - {title: "Job speed date", image: "workshop.jpg", text: "You get 4–5 minutes with each company and then move on. It aims for both companies and developers to see what’s out there." }
 - {title: "IT kviz", image: "quiz.jpg", text: "Imagine this:<br>
One big screen... 30 pick-the-right-answer questions... 3-5 person on a team... One paper...<br>
<br>
Do you have what it takes? Does your squad know more that those geeks at the table next to you? Only one way to find out, Lets Go!<br>
<br>
The winning team gets to have a really cool Google gift and Eternal Glory in IT Heaven!<br>
<br>
(Food & Drink are Yes but Googling answers is a No)<br>
<br>
Powered by <a href=\"http://hrkviz.hr/\">hrkviz.hr</a>"}

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "200", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "5", specialCharacter: "+", info: "hours", detail: "hours around web, mobile and cloud technology"}
 - {count: "4", specialCharacter: "+", info: "speakers", detail: "from Croatia and all over the world"}
 - {count: "1", specialCharacter: "", info: "track", detail: "plus entertainment lounge"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
eventLocationName: "HUB385"
locationBlockTitle: "Location"
eventLocationLink: "https://hub385.com/"
eventStreetAddress: "Petračićeva 6"
eventAddressLocality: "Zagreb"
eventAddressLocalityRegion: "Grad Zagreb"
eventPostalCode: "10000 "
eventAddressCountry: "Croatia"
eventStartTime: "2018-12-01T09:00"
eventDoorTime: "09:00"
eventEndTime: "2018-12-01T14:00"
eventPlaceCoordinates: "45.8074235,15.9549643"
mapCenterCoordinates: "45.8074235,15.9549643"
mapMobileCenterCoordinates: "45.8074235,15.9549643"
eventLocationFindWayArrows: false

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "At awesome HUB385"
venueFeatures: ["First floor: Show - And - Tell and Job - Speed - Dating area!", "Second floor: Sessions, Talks, Quiz and so much more!"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "devfest"
twitterFeed: ""

# Partners Block
# organizersTitle: "Organizers"
# partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Student"
  price: "25"
  priceCurrency: "HRK"
  ticketsNumber: "150"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ribbon: "-93%"
  buyButtonLink: "https://www.entrio.hr/event/devfest-croatia-2018-5664"
  buyButtonText: "Buy Now"
  ticketContentList: ["Conference", "Job speed date", "Lunch", "* Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"]
  validFrom: "2018-11-01T10:00"
  validThrough: "2018-12-1T23:59"
  # disabled: true
 -
  name: "Early bird"
  price: "250"
  priceCurrency: "HRK"
  ticketsNumber: "20"
  ribbon: "-30%"
  buyButtonLink: "https://www.entrio.hr/event/devfest-croatia-2018-5664"
  buyButtonText: "Buy Now"
  featured: true
  ticketContentList: ["Conference", "Job speed date", "Lunch", "* This offer is valid only for first 20 tickets."]
  validFrom: "2018-11-01T10:00"
  validThrough: "2018-12-1T23:59"
  # soldOut: true
  # soldOutText: "Sold Out"
 -
  name: "Regular"
  price: "350"
  priceCurrency: "HRK"
  ticketsNumber: "250"
  buyButtonLink: "https://www.entrio.hr/event/devfest-croatia-2018-5664"
  buyButtonText: "Buy Now"
  ticketContentList: ["Conference", "Job speed date", "Lunch"]
  validFrom: "2018-11-01T10:00"
  validThrough: "2018-12-1T23:59"
  # soldOut: true
  # soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://mobile.twitter.com/hashtag/DevFest", icon: "twitter"}
 - {link: "https://www.facebook.com/gdgzagreb/", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://www.meetup.com/gdg-zagreb", text: "GDG Zagreb"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:devfest.croatia@gmail.com", text: "devfest.croatia@gmail.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfesthr"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
