# Plugins
plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME', vendor]


# Site Settings
title: "Build IT Right 2020"
email: "bitrconference@gmail.com"
description: "Build IT Right is a conference for people interested in
IT based in Newcastle Upon Tyne"
baseurl: ""
url: "https://bitr.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-122482205-1"
googleAnalyticsSiteUrl: "bitrconf.org"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "Fiona Hobbs"
organizerAlternateName: "Chris Howe-Jones"
organizerDescription: "Software Developers, Agile/Lean coaches with a
strong interest in promoting software development in the North East of
England."
organizerEmail: "bitrconference@gmail.com"
organizerLogo: "/img/seo/beaconhouse-logo.png"
organizerLink: "http://www.beaconhouse-events.co.uk/"

# Head
metaKeywords: "event, bitr, BuildITRight, software, programming,
agile, lean, developers, newcastle, tyne and wear, north east england"
twitterAccount: "@bitr"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "http://bit.ly/2NzkBtb"
c4sponsorsUrl: "/assets/BITR_2019_Sponsorship&Exhibition_Pack.pdf"

# Speakers
speakerButtonMessage: "Become a speaker"
speakerEmailAddress: "bitrconference@gmail.com"
speakerEmailSubject: "I’d like to find out more about speaking"

# Sponsors
sponsorButtonMessage: "Become a sponsor"
sponsorEmailAddress: "bitrconference@gmail.com"
sponsorEmailSubject: "I’d like to find out more about sponsoring"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Schedule"}
# - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Logistics"}
 - {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 - {link: "mailto:bitrconference@gmail.com?subject=I’d like to find out more about speaking", text: "Become a speaker"}
 - {link: "mailto:bitrconference@gmail.com?subject=I’d like to find out more about sponsoring", text: "Become a sponsor"}
 - {permalink: "/#tickets", text: "Buy tickets"}
rightNavigationButtons:
 - {permalink: "/#tickets", text: "Buy tickets"}
 - {link: "mailto:bitrconference@gmail.com?subject=I’d like to find out more about sponsoring", text: "Become a sponsor"}
 - {link: "mailto:bitrconference@gmail.com?subject=I’d like to find out more about speaking", text: "Become a speaker"}


# Hero Block
heroImage: "newcastle-bridges.jpg"
heroTitle: "Build IT Right <typeout> 2020"
eventDate: "26th March, 2020"
#typeoutTextValues: '"Newcastle Upon Tyne", "UK"'
typeoutFallback: "Newcastle Upon Tyne"
heroButtons:
 - {link: "mailto:bitrconference@gmail.com?subject=I’d like to find out more about speaking", text: "Become a speaker"}
 - {link: "mailto:bitrconference@gmail.com?subject=I’d like to find out more about sponsoring", text: "Become a sponsor"}
 - {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "About Build IT Right"
aboutBlock:
 - {title: "Conference", image: "Simon_Brown.jpg", text: "Build IT Right returns in 2020 with another day of engaging and informative
  content for all software professionals in the North East. The lightning talks, exhibition and panel session will be back to Keynote
  speakers will be announced shortly, and once again we’ll have a Call for Papers to fill the tracks, <b>Architecture</b>, <b>Development Process</b>,
  <b>Development Technologies</b> and <b>UX & UR</b>. The event provides delegates with a dedicated day away from their screens, expand knowledge, and
  inspire how to adapt to emerging trends." }

# Feedback Block
feedbackTitle: "Feedback from 2019"
feedbackBlock:
  -
    text: "Well-organised, interesting and thought-provoking content and ideas, and no travel approval required to attend!"
    person:
    position: "2019 Delegate"

  -
    text: "#BITRConf was a fantastic event, and I’ve had a <b>really</b> fun day"
    person: "Simon Brown"
    position: Keynote 2019



# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "300", specialCharacter: "+", info: "attendees", detail: "from near and far"}
 - {count: "15", specialCharacter: "+", info: "hours", detail: "of discussions on effective software development"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from the UK and beyond"}
 - {count: "4", specialCharacter: "", info: "parallel tracks", detail: "plus the most interesting 'water cooler' talk outside the talks"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 3
rockstarSpeakersTitle: "World class speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Crowne Plaza Hotel, Newcastle Upon Tyne"
eventLocationLink: "http://bit.ly/2L1b78j"
eventStreetAddress: "Hawthorn Square, Forth Street"
eventAddressLocality: "Newcastle Upon Tyne"
eventAddressLocalityRegion: "Tyne and Wear"
eventPostalCode: "NE1 3SA"
eventAddressCountry: "United Kingdom"
eventStartTime: "2020-03-26T08:00"
eventDoorTime: "07:30"
eventEndTime: "2020-03-26T18:00"
eventPlaceCoordinates: "54.967145, -1.616574"
mapCenterCoordinates: "54.967145, -1.616574"
mapMobileCenterCoordinates: "54.967145, -1.616574"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Crowne Plaza Hotel"
venueFeatures: ["Spa and fitness suite", "Wi-Fi in all rooms and public areas", "Located in the Stephenson Quarter in the city centre"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "bitrconf"
twitterFeed: "http://twitter.com/bitrconf"

# Partners Block
organizersTitle: "Organisers"
#partnersTitle: "Partners"
partnersTitle: "Sponsors"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://github.us18.list-manage.com/subscribe/post?u=440fd2edca6e5128f8dd511bf&amp;id=883fca8761"
subscribeInfo: "Number of tickets are limited - Stay tuned!"

# Tickets Block
hideTicketsBlock: true
ticketsTitle: "Pricing"
ticketsSubTitle: "Additional information"
# ticketsInfo: "Tickets grant access to all conference sections, coffee breaks, lunch and party. Accommodation is NOT included in the ticket price."
ticketsInfo: "Tickets grant access to all conference sections, coffee breaks and lunch. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Standard"
  price: "£150"
  priceCurrency: "+ VAT"
  ticketsNumber: "200"
  featured: false
  ribbon: "Full price"
  buyButtonLink: "https://www.eventbrite.co.uk/e/build-it-right-conference-2020-tickets-60809762637?"
  buyButtonText: "Buy Now"
  ticketContentList: ["Access to all talks"]
  validFrom: "2019-12-01T10:00"
  #validThrough: "2018-11-20T23:59"
  validThrough: "2020-03-25T23:59"
  soldOut: false
  hide: false
 -
  name: "Early Bird"
  price: "£99"
  priceCurrency: "+ VAT"
  ticketsNumber: "50"
  featured: true
  ribbon: "-33%"
  buyButtonLink: "https://www.eventbrite.co.uk/e/build-it-right-conference-2020-tickets-60809762637?"
  buyButtonText: "Buy Now"
  ticketContentList: ["Access to all talks"]
  validFrom: "2019-05-07T10:00"
  #validThrough: "2018-08-31T23:59"
  validThrough: "2020-11-30T23:59"
  soldOut: false
  hide: false
 -
  name: "Concessionary"
  price: "£99"
  priceCurrency: "+ VAT"
  ticketsNumber: "50"
  featured: false
  buyButtonLink: "https://www.eventbrite.co.uk/e/build-it-right-conference-2020-tickets-60809762637?"
  buyButtonText: "Buy Now"
  additionalInfo: "Students require a valid student email address at time of purchase."
  ticketContentList: ["Access to all talks"]
  validFrom: "2019-12-01T10:00"
  #validThrough: "2018-11-20T23:59"
  validThrough: "2020-03-25T23:59"
  soldOut: false
  hide: false

# Footer
socialLinks:
 #- {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://twitter.com/bitrconf", icon: "twitter"}
 #- {link: "https://facebook.com/GDGLviv", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www.beaconhouse-events.co.uk", text: "BeaconHouse Events"}
   - {link: "https://www.ihg.com/crowneplaza/hotels/gb/en/newcastle-upon-tyne/nclsq/hoteldetail", text: "Crowne Plaza Newcastle"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:bitrconference@gmail.com", text: "bitrconference@gmail.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "bitrconf"

# Speakers List Block
showSessions: true

# Speakers Support
supportTitle: "With support from"
supportImages:
- {name: "Dynamo", description: "Dynamo, Growing the North East IT economy", link: "http://www.dynamonortheast.co.uk/kids-digital-maker-party/", imageUrl: "Dynamo_Primary_Pant164_No_Strap.png"}
- {name: "ERDF", description: "European Regional Development Fund", link: "http://ec.europa.eu/regional_policy/en/funding/erdf/", imageUrl: "EU-ERDF-EN-2000px.png"}

# Team Block
teamBlockTitle: "About us"
aboutUs: "The North East of England and Newcastle Upon Tyne in
particular has a long tradition of software development. This
conference is intended to showcase the best talent in the region while
challenging established precedent in how software is built."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "54.967145, -1.616574"
logisticsMapMobileCenterCoordinates: "54.967145, -1.616574"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Newcastle"
directionDetailsCards:
 - {title: "From the Airport", information: 'Newcastle International Airport is situated six miles north-west of the city. It is easily reachable by car, public transport or taxi. More information is available on the <a href="https://www.newcastleairport.com/getting-here" target="_blank">airport website</a>.'}
 - {title: "Public Transit", information: 'Newcastle is well served by public transport including local bus routes and the Tyne and Wear Metro. See the
 <a href="https://www.nexus.org.uk/" target="_blank">Nexus website</a> for more details.'}
 - {title: "Hotels", information: 'Newcastle has lots of great hotels and hostels. More information can be found in the <a href="#questions">questions</a> section below.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "http://bit.ly/2L1b78j", text: "Crowne Plaza Newcastle"}
     - {link: "https://www.jurysinns.com/hotels/newcastle/newcastle", text: "Jurys Inn Newcastle"}
     - {link: "https://www.travelodge.co.uk/hotels/633/Newcastle-Quayside-hotel", text: "Travelodge Newcstle Quayside"}
     - {link: "http://www.sleeperz.com/newcastle", text: "Sleeperz Newcastle"}
     - {link: "https://www.ihg.com/holidayinnexpress/hotels/gb/en/newcastle-upon-tyne/ncljb/hoteldetail", text: "Holiday Inn Express Newcastle City Centre"}
   -
    title: "Registration"
    links:
     - {link: "http://bit.ly/2L1b78j", text: "Crowne Plaza Newcastle"}
   -
    title: "Attendance Details"
    links:
     - {link: "http://bit.ly/2L1b78j", text: "Crowne Plaza Newcastle"}

# Hackathon
hackathonTitle: "Hack-NE-thing"
enableHackathon: false

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Alexa Skills Kit Challenge", image: "echo-dot.jpg", details: "Help out a charity by building an app using the Alexa Skills Kit. Come up with an
 idea for how to contribute to local North East charities using Alexa. Build something in a lunchtime.&nbsp;<a href
 ='https://developer.amazon.com/alexa-skills-kit'>Alexa Skills Kit</a>"}
 - {title: "Mobile App Challenge", image: "iphone.jpg", details: "Help out a charity by building a mobile app using whatever technology you fancy. Come up with an
 idea for how to contribute to local North East charities. Assemble a team of fellow attendees with a mix of UX, development
 and testing skills and see what you can build in an hour or so."}
 - {title: "Come up with your own idea", image: "question-mark.jpg", details: "Help out a charity by building whatever you like using whatever technology you fancy. Come up with an
 idea for how to contribute to local North East charities. Assemble a team of fellow attendees with a mix of UX, development
 and testing skills and see what you can build in an hour or so."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "Watch this space!", image: "echo-dot.jpg", info: "Watch this space for announcements on prizes."}
 # - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 # - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 # - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Crowne Plaza Newcastle"
hackathonLocationLink: "http://bit.ly/2L1b78j"
hackathonStreetAddress: "Hawthorn Square, Forth Street"
hackathonAddressLocality: "Newcastle Upon Tyne"
hackathonAddressLocalityRegion: "Tyne and Wear"
hackathonPostalCode: "NE1 3SA"
hackathonAddressCountry: "United Kingdom"
hackathonTimeTitle: "Hack-NE-thing"
hackathonStartTime: "2020-03-26T12:30"
hackathonDoorTime: "09:00"
hackathonEndTime: "2020-03-26T14:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "54.967145, -1.616574"
hackathonMapCenterCoordinates: "54.967145, -1.616574"
hackathonMapMobileCenterCoordinates: "54.967145, -1.616574"
