# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Java.next(2016)"
email: "jnext.openspace@gmail.com"
description: "Un open space sobre el futuro de Java"
baseurl: "/jnext"
url: "https://jnext.eu"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-74341480-1"
googleAnalyticsSiteUrl: "jnext.eu"
siteVerification: "_GYqmHGjILSQ0LnKgufxx7wH5tn3oS3WdPKe200j_gs"

# Organizer Info
organizerName: "Madrid JUG"
organizerAlternateName: "Madrid Java User Group"
organizerDescription: "Madrid Java User Group (MadridJUG) es un grupo de desarrolladores cuyo interés es compartir el conocimiento y realizar actividades en torno a Java y la JVM."
organizerEmail: "madridjavausergroup@gmail.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://www.meetup.com/MadridJUG/"

# Head
metaKeywords: "evento, jug, open space, java, jvm, futuro, programacion, desarrolladores, madrid, madridjug, talentum empleo"
twitterAccount: "@jnext_openspace"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://jnext.eu/#"
c4sponsorsUrl: "/assets/#"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Logistics"}
bottomNavigationLinks:
 - {link: "http://is.gd/jGJodX", text: "¿Qué es un Open Space?"}
rightNavigationButtons:
 - {link: "http://is.gd/jGJodX", text: "¿Qué es un Open Space?"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Java.next(2016) <typeout>"
eventDate: "2 de Abril de 2016"
typeoutTextValues: '"", "//Open Space", "//El futuro de Java"'
typeoutFallback: '""'
heroButtons:
 - {link: "http://is.gd/jGJodX", text: "¿Qué es un Open Space?"}
 - {permalink: "/#tickets", text: "Compra tu entrada"}

# About Block
aboutTitle: "About GDG DevFest"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "The biggest Google related event in the country carefully crafted for you by GDG community! Awesome speakers and lots of fun!" }
 - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
 - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "¿Dónde?"
eventLocationName: "Campus Sur de la UPM (Carretera de Valencia), ETSI de Sistemas Informáticos"
eventLocationLink: "https://www.etsisi.upm.es/campus_sur"
eventStreetAddress: "Universidad Politécnica de Madrid, Calle Alan Turing, s/n"
eventAddressLocality: "Madrid"
eventAddressLocalityRegion: "Madrid"
eventPostalCode: "28031"
eventAddressCountry: "Spain"
eventStartTime: "2016-04-02T10:00"
eventDoorTime: "09:00"
eventEndTime: "2016-04-02T20:00"
eventPlaceCoordinates: "40.3896044, -3.6298781"
mapCenterCoordinates: "40.3896044, -3.6298781"
mapMobileCenterCoordinates: "40.3896044, -3.6298781"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Kinopalace Cinema"
venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "Últimos tuits"
twitterHashTag: "jnext16"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Last Chance"
  price: "450"
  priceCurrency: "UAH"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-10-01T00:00"
  validThrough: "2014-10-23T23:59"
  disabled: true
 -
  name: "Student"
  price: "200"
  priceCurrency: "UAH"
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"
  soldOut: true
  soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://twitter.com/intent/user?screen_name=jnext_openspace", icon: "twitter"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www.meetup.com/MadridJUG/", text: "MadridJUG Meetup"}
   - {link: "http://talentumempleo.com/", text: "Talentum Empleo"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:madridjavausergroup@gmail.com", text: "madridjavausergroup@gmail.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Coordenadas"
findWayDistance: "Distancia"
findWayDriving: "EN COCHE"
findWayWalking: "ANDANDO"
findWayBicycling: "EN BICI"
findWayTransit: "TRANSPORTE PÚBLICO"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "40.3886779, -3.7705158"
logisticsMapMobileCenterCoordinates: "40.3886779, -3.7705158"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Llegar a Madrid"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

