version: "2"
services:
  web:
    build: .
    volumes:
      - .:/app
      - bundle:/bundle
    ports:
      - "80:80"
    environment:
      - LANG=C.UTF-8
    command:
      bundle exec jekyll serve -H 0.0.0.0 -P 80 --future
    entrypoint:
      ./docker-entrypoint.sh
volumes:
  bundle:
