# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "BSides Halifax Quarantine Edition"
email: "info@bsideshalifax.ca"
description: "BSides is a community-driven framework for building events for and by information security community members."
baseurl: ""
url: "https://bsideshalifax.ca/2020"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-165605284-1"
googleAnalyticsSiteUrl: "gdg-x.github.io"
siteVerification: "U2vM0e028DKxBzX3zvCNmR2ZQk31oXU5asShWbU3Oqg"

# Organizer Info
organizerName: "BSides Halifax"
organizerAlternateName: "Halifax BSides"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Cyber Security with passion."
organizerEmail: "info@bsideshalifax.ca"
organizerLogo: "/2020/img/seo/organizer-logo.png"
organizerLink: "https://bsideshalifax.ca/2020"

# Head
metaKeywords: "event, BSides, Halifax, Cyber, Security, infosec"
twitterAccount: "@HalifaxBSides"
socialImageSrcTwitter: "/2020/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/2020/img/seo/sharing-facebook.png"

# Documents
c4sponsorsUrl: "/2020/assets/BSides_HFX_Sponsorship_Kit.pdf"


# Navigation
navigationLinks:
 - {permalink: "/2020/", text: "Home"}
 - {permalink: "/2020/schedule/", text: "Schedule"}
 - {permalink: "/2020/speakers/", text: "Speakers"}
 - {permalink: "/2020/team/", text: "Team"}
 - {permalink: "/2020/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
- {link: "/2020/assets/BSides_HFX_Sponsorship_Kit.pdf", text: "Become a sponsor"}

# Hero Block
heroImage: "halifax.jpg"
heroTitle: "BSides Halifax <typeout> 2020"
eventDate: "Friday May 22, 2020"
typeoutTextValues: '"", "Virtual", "Quarantine Edition", "Stay The Blazes Home", "Donair Bonanza"'
typeoutFallback: "Virtual"
heroButtons:
 - {permalink: "/2020/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "About BSides Halifax"
aboutBlock:
 - {
    title: "Conference",
    image: "conference.jpg",
    text: "<p>In Halifax, we usually host a conference called AtlSecCon (Atlantic Security Conference) this time of year. And 2020 was going to be the best year ever! It was the tenth anniversary, and everyone was really looking forward to a party... in a big crowded room... with plenty of people constantly breathing in and out...</p>
<p>Anyway, things have changed, and AtlSecCon's tenth anniversary will now be held in 2020++ (aka 2021). But that doesn't mean security takes a break!</p>
<p>In fact, since we're all online more than ever, it's the perfect time to examine your personal and professional security posture, to see if there's anything that could be improved, or any holes that need patching.</p>
<p>We'll be hosting BSides Halifax on May 22nd, and you can attend from the safety of your home/secured bunker/government-mandated temporary quarantine facility by logging on to bsideshalifax.ca at 10AM Atlantic (9AM Eastern).</p>
<p>We're really appreciative of everyone who's come forward to help us out with this. Tickets are $13.37 CAD, and all money raised will go to Feed Nova Scotia, who make sure no Nova Scotian goes hungry. We look forward to seeing you all soon!</p>"
}

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "4", specialCharacter: "+", info: "hours", detail: "of amazing talks"}
 - {count: "6", specialCharacter: "", info: "speakers", detail: "from across North America"}
 - {count: "24", specialCharacter: "", info: "hours", detail: "of CTF hacking goodness"}

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 3
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Tickets Block
ticketsTitle: "Tickets"
ticketsInfo: "All proceeds go to Feed Nova Scotia"
ticketsOffers:
 -
  name: "General Admittance"
  price: "13.37"
  priceCurrency: "CAD"
#   ticketsNumber: "150"
#   ribbon: "-5%"
  buyButtonLink: "https://www.eventbrite.ca/e/security-bsides-halifax-2020-virtual-tickets-104057223958?aff=ebdssbeac"
  buyButtonText: "Buy Now"
  ticketContentList: ["Access to amazing talks", "Admittance to our CTF", "Our everlasting love and admiration", "All proceeds go to Feed Nova Scotia"]
#   validFrom: "2014-08-25T10:00"
#   validThrough: "2014-09-30T23:59"

# Footer
socialLinks:
 - {link: "https://twitter.com/intent/user?screen_name=HalifaxBSides", icon: "twitter"}
 - {link: "https://discord.gg/aGzzj4B", icon: "site"}
 - {link: "https://github.com/bsideshalifax", icon: "github"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www.securitybsides.com/w/page/12194156/FrontPage", text: "Security BSides", icon: "site"}
   - {link: "https://atlseccon.com", text: "Atlantic Security Conference", icon: "site"}
   - {link: "https://dc902.ca", text: "DEFCON Halifax", icon: "site"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:info@bsideshalifax.ca", text: "info@bsideshalifax.ca", icon: "email"}
 -
  title: "Code of Conduct"
  links:
   - {permalink: "/2020/cod/", text: "Code of Conduct"}

# Speakers List Block
showSessions: false

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "CMD+CTRL"
hackathonRows:
   - {title: "", image: "hackathon-0.png", details: "<p>Stuck at home, but still want to test your skills in identifying web app vulnerabilities?  BSides Halifax and Security Innovation invite players to virtually compete in CMD+CTRL, a web application cyber range where players exploit their way through hundreds of vulnerabilities that lurk in business applications today.  Success means learning quickly that attack and defense is all about thinking on your feet.</p>
<p>For each vulnerability you uncover, you are awarded points. Climb the interactive leaderboard for a chance to win fantastic prizes! CMD+CTRL is ideal for development teams to train and develop skills, but anyone involved in keeping your organizationâ€™s data secure can play - from developers and managers and even CISOs.</p>
<p>All you need is your laptop and inner evil-doer!</p>
<br />
<p>Register early to reserve your spot and get a sneak peek at our cheat sheets and FAQs!</p>"}

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Hak5 Bash Bunny"}
 - {title: "1st Place", image: "prize-1.jpg", info: "Hak5 WiFi Pineapple"}
 - {title: "3rd Place", image: "prize-3.jpg", info: "Hak5 Packet Squirrle"}
